/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Jan 12 22:10:13 2019. */

#include "index.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t commands_Empty_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t commands_MessageEvent_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, commands_MessageEvent, event, event, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, commands_MessageEvent, id, event, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, commands_MessageEvent, message, id, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
