/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Jan 12 22:10:13 2019. */

#include "KeyPress.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t events_KeyPress_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, events_KeyPress, key_code, key_code, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
